language: python
python:
  - 2.7
  - pypy
  - 3.5
  - 3.4
  - 3.3
  - 3.2
  - pypy3
env:
  global:
    - SYMPY_SRC=sympy-1.0
    - DOC="false"
    - ALL_MODULES="false"
    - CYTHON="false"
matrix:
  fast_finish: true
  include:
    - python: 2.7
      env: DOC="true"
    - python: 3.5
      env: DOC="true"
    - python: 2.7
      env: SYMPY_SRC=master
    - python: 3.5
      env: SYMPY_SRC=master
    - python: 2.7
      env: ALL_MODULES="true"
    - python: 3.5
      env: ALL_MODULES="true"
    - python: pypy
      env: ALL_MODULES="true"
    - python: 2.7
      env: CYTHON="true"
    - python: 3.5
      env: CYTHON="true"
    - python: 2.7
      env: ALL_MODULES="true" CYTHON="true"
    - python: 3.5
      env: ALL_MODULES="true" CYTHON="true"
  allow_failures:
    - python: 3.2
    - python: pypy3
    - env: SYMPY_SRC=master
    - env: DOC="true"
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - echo "build.sh"
  - cat /home/travis/build.sh 
  - export CURRDIR = "$PWD"
  - sudo apt-get update  &&
  - pip install numpy scipy matplotlib &&
  - cd /tmp; git clone git@github.com:mmatera/Mathics.git; cd Mathics; python setup.py install; cd $CURRDIR &&
  - echo "$PWD"
  - if [[ "$DOC" == "true" ]]; then
      sudo apt-get update -qq &&
      sudo apt-get install -qq asymptote imagemagick texlive-latex-extra texlive-latex3 texlive-fonts-recommended latexmk;
    fi
  - if [[ "$CYTHON" == "true" ]]; then
      pip install cython;
    fi
  - pip install unittest2
  - pip install pexpect
install:
  - sed -i "s/'sympy==[0-9]\.[0-9]\.[0-9]', //" setup.py
  - if [[ "$DOC" == "true" ]]; then python setup.py develop; else python setup.py install; fi
script:
  - python setup.py test
  - if [[ "$DOC" == "true" ]]; then
       python test.py -o -l &&
       python test.py -t -l &&	
       cd doc/ &&
       mkdir tex &&
       cd tex/ &&
       make latex;      
    else
      	 python mathics/test.py -l;
    fi
notifications:
    email: false
    slack: mathics:VIjdkcZPlA79sOtVOtyjdOcT
